# Generated by Django 3.0.5 on 2022-05-03 16:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_auto_20220503_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='1234567890', max_length=128, region=None, unique=True),
        ),
    ]
