# Generated by Django 3.0.5 on 2022-05-03 18:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_auto_20220503_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='1234567890', max_length=128, null=True, region=None, unique=True),
        ),
    ]
