# Generated by Django 3.0.5 on 2022-05-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_patient_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(null=True, upload_to='hospital/static/hospital/profile_pics'),
        ),
    ]
