# Generated by Django 3.0.5 on 2022-05-03 21:45

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_auto_20220503_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='1234567890', max_length=128, null=True, region=None),
        ),
    ]
